version: '3.8'
services:
  stats-gateway:
    build: stat-service/stat-gateway
    image: stat-gateway
    container_name: stat-gateway
    ports:
      - "9091:9091"
    depends_on:
      - stats-server
    environment:
      - STAT_GATEWAY_PORT=9091
      - STAT_SERVER_URL=http://stats-server:9090

  stats-server:
    build: stat-service/stat-server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STAT_SERVER_PORT=9090
      - POSTGRES_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-server:
    build: ewm-service/ewm-main
    image: ewm-main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-gateway
    environment:
      - MAIN_SERVER_PORT=8080
      - POSTGRES_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - STAT_CLIENT_URL=http://stats-gateway:9091

  stats-db:
    image: postgres:16.0-alpine3.18
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6667:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-db:
    image: postgres:16.0-alpine3.18
    container_name: ewm-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres