server:
  port: ${STAT_SERVER_PORT}
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  sql:
    init:
      mode: always
  jackson:
    serialization:
      write-dates-as-timestamps: false